package com.eric.stock.generate;

import java.io.Serializable;

public class Stock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_tbl.id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_tbl.product_id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_tbl.count
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_tbl.id
     *
     * @return the value of stock_tbl.id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_tbl.id
     *
     * @param id the value for stock_tbl.id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_tbl.product_id
     *
     * @return the value of stock_tbl.product_id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_tbl.product_id
     *
     * @param productId the value for stock_tbl.product_id
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_tbl.count
     *
     * @return the value of stock_tbl.count
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_tbl.count
     *
     * @param count the value for stock_tbl.count
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}