package com.eric.stock.generate;

import com.eric.stock.generate.Stock;
import com.eric.stock.generate.StockExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    long countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    List<Stock> selectByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    Stock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_tbl
     *
     * @mbg.generated Mon Jan 10 11:45:25 CST 2022
     */
    int updateByPrimaryKey(Stock record);
}